<?php 
include("includes/header.php");
?>
	
<main class="flex-shrink-0" style="margin-bottom:25rem" > 
    <section class="profile-banner" id="profile">
      <div class="container">
        <div class= "container card shadow-lg">
		<div class="header d-flex align-items-center"> 
		<div class="highlight"> Privacy Policy </div> 
		</div>
		<div class="card-body" id="choose_plan" style="overflow-y:scroll;height:500px;">			
			<div class=" row d-flex align-items-center justify-content-center">
			
				<div > 
					
					
				<p style='margin-right:0cm;margin-left:0cm;font-size:15px;font-family:"Calibri","sans-serif";margin-top:0cm;margin-bottom:.0001pt;line-height:15.0pt;text-align:justify;background:white;'><strong><span style='font-size:16px;font-family:"Calisto MT","serif";color:black;'>What does our privacy policy cover?</span></strong></p>
			<p style='margin-right:0cm;margin-left:0cm;font-size:15px;font-family:"Calibri","sans-serif";margin-top:0cm;margin-bottom:.0001pt;line-height:15.0pt;text-align:justify;background:white;'><span style='font-size:16px;font-family:"Calisto MT","serif";color:black;'><br>&nbsp;The objective of the privacy policy is to inform you regarding the processing of your personal information collected during your visit to our website / mobile application. This policy applies to current and former visitors of the website/application.</span></p>
			<p style='margin-right:0cm;margin-left:0cm;font-size:15px;font-family:"Calibri","sans-serif";margin-top:0cm;margin-bottom:.0001pt;line-height:15.0pt;text-align:justify;background:white;'><strong><span style='font-size:16px;font-family:"Calisto MT","serif";color:black;'>&nbsp;</span></strong></p>
			<div style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri","sans-serif";'>
			<ol start="1" style="margin-bottom:0cm;list-style-type: upper-alpha;margin-left:4.199999999999999px;">
			<li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri","sans-serif";'><strong><span style="font-size:12.0pt;color:black;">Collection and Use of Personal Information</span></strong></li>
			</ol>
			</div>
			<p style='margin-right:0cm;margin-left:0cm;font-size:15px;font-family:"Calibri","sans-serif";margin-top:0cm;margin-bottom:.0001pt;line-height:normal;text-align:justify;'><span style='font-size:16px;font-family:"Calisto MT","serif";color:black;'><br>&nbsp;Personal information (PI) - any information relating to an identified or identifiable living person, i.e. you or yours. In particular, we are using a common identifier such as a name, an identification number, location data, an online identifier or any other social identity of that natural person.</span></p>
			<p style='margin-right:0cm;margin-left:0cm;font-size:15px;font-family:"Calibri","sans-serif";margin-top:0cm;margin-bottom:.0001pt;line-height:15.0pt;text-align:justify;background:white;'><span style='font-size:16px;font-family:"Calisto MT","serif";color:black;'>The company respects the privacy of the Services users and is committed to protecting it in all respects. The information about the user as collected by the company is:</span></p>
			<p style='margin-right:0cm;margin-left:0cm;font-size:15px;font-family:"Calibri","sans-serif";margin-top:0cm;margin-bottom:.0001pt;line-height:15.0pt;text-align:justify;background:white;'><span style='font-size:16px;font-family:"Calisto MT","serif";color:black;'><br> <strong>B. information you provide to us</strong></span></p>
			<p style='margin-right:0cm;margin-left:0cm;font-size:15px;font-family:"Calibri","sans-serif";margin-top:0cm;margin-bottom:.0001pt;line-height:normal;text-align:justify;'><span style='font-size:16px;font-family:"Calisto MT","serif";color:black;'><br> <strong>Information Collected When you use our Website</strong></span></p>
			<p style='margin-right:0cm;margin-left:0cm;font-size:15px;font-family:"Calibri","sans-serif";margin-top:0cm;margin-bottom:.0001pt;line-height:normal;text-align:justify;'><span style='font-size:16px;font-family:"Calisto MT","serif";color:black;'><br>&nbsp;We may hold personal information about you, including, but not limited to, the following:</span></p>
			<ul style="list-style-type: disc;margin-left:44.75px;">
			<li><span style='font-family:"Calisto MT","serif";font-size:12.0pt;color:black;'>Name/User name</span></li>
			<li><span style='font-family:"Calisto MT","serif";font-size:12.0pt;color:black;'>Email id</span></li>
			<li><span style='font-family:"Calisto MT","serif";font-size:12.0pt;color:black;'>Contact Number</span></li>
			<li><span style='font-family:"Calisto MT","serif";font-size:12.0pt;color:black;'>Gender</span></li>
			<li><span style='font-family:"Calisto MT","serif";font-size:12.0pt;color:black;'>Location</span></li>
			<li><span style='font-family:"Calisto MT","serif";font-size:12.0pt;color:black;'>User Address (street address, city, state/province, zip/postal code, country)</span></li>
			<li><span style='font-family:"Calisto MT","serif";font-size:12.0pt;color:black;'>Photographs</span></li>
			<li><span style='font-family:"Calisto MT","serif";font-size:12.0pt;color:black;'>IP Address</span></li>
			</ul>
			<p style='margin-right:0cm;margin-left:0cm;font-size:15px;font-family:"Calibri","sans-serif";margin-top:0cm;margin-bottom:.0001pt;line-height:normal;text-align:justify;'><span style='font-size:16px;font-family:"Calisto MT","serif";color:black;'><br>&nbsp;We may also collect payment-related data for subscription services; however, we do not store any card data in our environment.</span></p>
			<p style='margin-right:0cm;margin-left:0cm;font-size:15px;font-family:"Calibri","sans-serif";margin-top:0cm;margin-bottom:.0001pt;line-height:15.0pt;text-align:justify;background:white;'><span style='font-size:16px;font-family:"Calisto MT","serif";color:black;'>You may allow us to access your camera or photo album to add certain content, like pictures.</span></p>
			<p style='margin-right:0cm;margin-left:0cm;font-size:15px;font-family:"Calibri","sans-serif";margin-top:0cm;margin-bottom:.0001pt;line-height:normal;text-align:justify;'><span style='font-size:16px;font-family:"Calisto MT","serif";color:black;'><br> <strong>Information Collected When you use our Mobile Application</strong></span></p>
			<p style='margin-right:0cm;margin-left:0cm;font-size:15px;font-family:"Calibri","sans-serif";margin-top:0cm;margin-bottom:.0001pt;line-height:normal;text-align:justify;'><span style='font-size:16px;font-family:"Calisto MT","serif";color:black;'><br>&nbsp;When you download our mobile application (related to our various services), we collect the below information, but not limited-</span></p>
			<ul style="list-style-type: disc;margin-left:44.75px;">
			<li><span style='font-family:"Calisto MT","serif";font-size:12.0pt;color:black;'>User Name</span></li>
			<li><span style='font-family:"Calisto MT","serif";font-size:12.0pt;color:black;'>Email id</span></li>
			<li><span style='font-family:"Calisto MT","serif";font-size:12.0pt;color:black;'>Mobile number</span></li>
			<li><span style='font-family:"Calisto MT","serif";font-size:12.0pt;color:black;'>Photograph</span></li>
			<li><span style='font-family:"Calisto MT","serif";font-size:12.0pt;color:black;'>Gender</span></li>
			<li><span style='font-family:"Calisto MT","serif";font-size:12.0pt;color:black;'>Device ID</span></li>
			</ul>
			<p style='margin-right:0cm;margin-left:0cm;font-size:15px;font-family:"Calibri","sans-serif";margin-top:0cm;margin-bottom:.0001pt;line-height:normal;text-align:justify;'><span style='font-size:16px;font-family:"Calisto MT","serif";color:black;'><br> <strong>Information you provide to us voluntarily</strong></span></p>
			<p style='margin-right:0cm;margin-left:0cm;font-size:15px;font-family:"Calibri","sans-serif";margin-top:0cm;margin-bottom:.0001pt;line-height:normal;text-align:justify;'><span style='font-size:16px;font-family:"Calisto MT","serif";color:black;'><br>&nbsp;We may collect additional information when you provide feedback(s), modify your content requirements or email preferences, respond to surveys, or communicate with us by posting a comment on our website/application or asking us a question through our feature or email. This information may include personal information such as but is not limited to, your name, email id, mobile number, comment, message etc.</span></p>
			<p style='margin-right:0cm;margin-left:0cm;font-size:15px;font-family:"Calibri","sans-serif";margin-top:0cm;margin-bottom:.0001pt;line-height:normal;text-align:justify;'><span style='font-size:16px;font-family:"Calisto MT","serif";color:black;'>&nbsp;</span></p>
			<p style='margin-right:0cm;margin-left:0cm;font-size:15px;font-family:"Calibri","sans-serif";margin-top:0cm;margin-bottom:.0001pt;line-height:normal;text-align:justify;'><strong><span style='font-size:16px;font-family:"Calisto MT","serif";color:black;'>&nbsp;</span></strong></p>
			<p style='margin-right:0cm;margin-left:0cm;font-size:15px;font-family:"Calibri","sans-serif";margin-top:0cm;margin-bottom:.0001pt;line-height:normal;text-align:justify;'><strong><span style='font-size:16px;font-family:"Calisto MT","serif";color:black;'>C. Information Automatically Collected/Tracked while Navigation</span></strong></p>
			<p style='margin-right:0cm;margin-left:0cm;font-size:15px;font-family:"Calibri","sans-serif";margin-top:0cm;margin-bottom:.0001pt;line-height:normal;text-align:justify;'><strong><span style='font-size:16px;font-family:"Calisto MT","serif";color:black;'>Cookies</span></strong><span style='font-size:16px;font-family:"Calisto MT","serif";color:black;'><br> To improve the responsiveness of the &quot;<strong>Services</strong>&quot; for our users, we may use &quot;</span><a href="https://www.jagranjosh.com/cookies-policy"><strong><span style='font-size:16px;font-family:"Calisto MT","serif";color:#333333;'>cookies</span></strong></a><span style='font-size:16px;font-family:"Calisto MT","serif";color:black;'>&quot; (a small text file that may be used, for example, to collect your information about Website/Application activity. Some cookies and other technologies may serve to recall Personal Information previously indicated by a user) or similar electronic tools to collect information to assign each visitor a unique, random number as a User Identification (&quot;<strong>User ID</strong>&quot;) to understand the user&apos;s interests using the identified computer. We receive and store certain types of information whenever you interact with us via Website (s), Application(s) or Services through your computer/laptop/notebook/ mobile/tablet/pad/handheld device or any other electronic device capable of connecting to the internet.</span></p>
			<p style='margin-right:0cm;margin-left:0cm;font-size:15px;font-family:"Calibri","sans-serif";margin-top:0cm;margin-bottom:.0001pt;line-height:normal;text-align:justify;'><span style='font-size:16px;font-family:"Calisto MT","serif";color:black;'><br>&nbsp;You may set most browsers to notify you if you receive a cookie, or you may choose to block cookies with your browser, but please note that if you choose to erase or block your cookies, you will need to re-enter your original user ID and password to gain access to certain parts of the Website/application, and some sections/features of the site/application may not work.</span></p>
			<p style='margin-right:0cm;margin-left:0cm;font-size:15px;font-family:"Calibri","sans-serif";margin-top:0cm;margin-bottom:.0001pt;line-height:normal;text-align:justify;'><span style='font-size:16px;font-family:"Calisto MT","serif";color:black;'><br>&nbsp;</span></p>
			<p style='margin-right:0cm;margin-left:0cm;font-size:15px;font-family:"Calibri","sans-serif";margin-top:0cm;margin-bottom:.0001pt;line-height:15.0pt;text-align:justify;background:white;'><strong><span style='font-size:16px;font-family:"Calisto MT","serif";color:black;'>D. Retention of Personal Information</span></strong></p>
			<p style='margin-right:0cm;margin-left:0cm;font-size:15px;font-family:"Calibri","sans-serif";margin-top:0cm;margin-bottom:.0001pt;line-height:normal;text-align:justify;'><span style='font-size:16px;font-family:"Calisto MT","serif";'>&nbsp;</span></p>
			<p style='margin-right:0cm;margin-left:0cm;font-size:15px;font-family:"Calibri","sans-serif";margin-top:0cm;margin-bottom:.0001pt;line-height:15.0pt;text-align:justify;background:white;'><span style='font-size:16px;font-family:"Calisto MT","serif";color:black;'>Your personal information processed by our site or application is kept in a form that permits your identification for no longer than is necessary for the purposes for which the personal information is processed in line with legal, regulatory, contractual or statutory obligations as applicable.</span></p>
			<p style='margin-right:0cm;margin-left:0cm;font-size:15px;font-family:"Calibri","sans-serif";margin-top:0cm;margin-bottom:.0001pt;line-height:15.0pt;text-align:justify;background:white;'><span style='font-size:16px;font-family:"Calisto MT","serif";color:black;'>Your personal information will be deleted or archived to comply with legal/contractual retention obligations or under applicable statutory limitation periods at the expiry of such periods.<br>&nbsp;<br> <strong>E. Monitoring</strong></span></p>
			<p style='margin-right:0cm;margin-left:0cm;font-size:15px;font-family:"Calibri","sans-serif";margin-top:0cm;margin-bottom:.0001pt;line-height:normal;text-align:justify;'><span style='font-size:16px;font-family:"Calisto MT","serif";'>&nbsp;</span></p>
			<p style='margin-right:0cm;margin-left:0cm;font-size:15px;font-family:"Calibri","sans-serif";margin-top:0cm;margin-bottom:.0001pt;line-height:15.0pt;text-align:justify;background:white;'><span style='font-size:16px;font-family:"Calisto MT","serif";color:black;'>To the extent permitted by law, AstroMart may record and monitor your communications with us to ensure compliance with our legal and regulatory obligations and our internal policies. This may include the recording of telephone conversations.</span></p>
			<p style='margin-right:0cm;margin-left:0cm;font-size:15px;font-family:"Calibri","sans-serif";margin-top:0cm;margin-bottom:.0001pt;line-height:15.0pt;text-align:justify;background:white;'><span style='font-size:16px;font-family:"Calisto MT","serif";color:black;'>&nbsp;</span></p>
			<p style='margin-right:0cm;margin-left:0cm;font-size:15px;font-family:"Calibri","sans-serif";margin-top:0cm;margin-bottom:10.0pt;line-height:107%;text-align:justify;'><strong><span style='font-family:"Calisto MT","serif";color:black;'>F. Others</span></strong></p>
			<p style='margin-right:0cm;margin-left:0cm;font-size:15px;font-family:"Calibri","sans-serif";margin-top:0cm;margin-bottom:10.0pt;line-height:107%;text-align:justify;'><strong><span style='font-family:"Calisto MT","serif";color:black;'>Links</span></strong></p>
			<p style='margin-right:0cm;margin-left:0cm;font-size:15px;font-family:"Calibri","sans-serif";margin-top:0cm;margin-bottom:10.0pt;line-height:107%;text-align:justify;'><span style='font-family:"Calisto MT","serif";color:black;'>We may present links in a format that lets us track whether these links have been followed. We use this information to improve our customized content. We encourage our users to be aware when they leave our site to read other websites&apos; privacy statements that collect personally identifiable information. This Privacy Policy applies solely to information collected by our Website.</span></p>
			<p style='margin-right:0cm;margin-left:0cm;font-size:15px;font-family:"Calibri","sans-serif";margin-top:0cm;margin-bottom:10.0pt;line-height:107%;text-align:justify;'><strong><span style='font-family:"Calisto MT","serif";color:black;'>Alerts</span></strong></p>
			<p style='margin-right:0cm;margin-left:0cm;font-size:15px;font-family:"Calibri","sans-serif";margin-top:0cm;margin-bottom:10.0pt;line-height:107%;text-align:justify;'><span style='font-family:"Calisto MT","serif";color:black;'>We may alert you by email or phone (through SMS/call) to inform you about new service offerings of the company and its subsidiaries/affiliates or other information which we feel might be useful for you through the company or its subsidiaries/affiliates.</span></p>
			<p style='margin-right:0cm;margin-left:0cm;font-size:15px;font-family:"Calibri","sans-serif";margin-top:0cm;margin-bottom:10.0pt;line-height:107%;text-align:justify;'><strong><span style='font-family:"Calisto MT","serif";color:black;'>&nbsp;</span></strong></p>
			<p style='margin-right:0cm;margin-left:0cm;font-size:15px;font-family:"Calibri","sans-serif";margin-top:0cm;margin-bottom:10.0pt;line-height:107%;text-align:justify;'><strong><span style='font-family:"Calisto MT","serif";color:black;'>&nbsp;</span></strong></p>
			<p style='margin-right:0cm;margin-left:0cm;font-size:15px;font-family:"Calibri","sans-serif";margin-top:0cm;margin-bottom:10.0pt;line-height:107%;text-align:justify;'><strong><span style='font-family:"Calisto MT","serif";color:black;'>Security</span></strong></p>
			<p style='margin-right:0cm;margin-left:0cm;font-size:15px;font-family:"Calibri","sans-serif";margin-top:0cm;margin-bottom:10.0pt;line-height:107%;text-align:justify;'><span style='font-family:"Calisto MT","serif";color:black;'>We are concerned about safeguarding the confidentiality of your information. Therefore, we provide physical, electronic, and procedural safeguards to protect the information we process and maintain. For example, we limit access to this information to authorized employees who only need to know that information to operate, develop or improve our Application/Services/products/Website. However, please be aware that although we endeavour to provide reasonable security for the information we process and maintain, no security system can prevent all potential security breaches.</span></p>
					
			</div>
			<button class="btn btn-primary btn-block btn-lg mt-3" type="button" style="width:auto !important;"><a href="home.php	" style="text-decoration:none;color:white;">Accept & Proceed</a></button>
		</div>
		</div>
     
    </section> 
	
</main>
 <?php include("includes/footer.php");?>
