<?php 
include("includes/header.php");
?>
	
<main class="flex-shrink-0" style="margin-bottom:25rem" > 
    <section class="profile-banner" id="profile">
      <div class="container">
        <div class= "container card shadow-lg">
		<div class="header d-flex align-items-center"> 
		<div class="highlight"> Terms</div> 
		</div>
		<div class="card-body" id="choose_plan" style="overflow-y:scroll;height:500px;">			
			<div class=" row d-flex align-items-center justify-content-center">
			<div > 
				<p style='margin-top:6.0pt;margin-right:0cm;margin-bottom:6.0pt;margin-left:0cm;line-height:14.4pt;font-size:16px;font-family:"Calisto MT","serif";text-align:justify;background:white;'><strong><span style='font-family:"Calibri","sans-serif";color:#333333;'>TERMS OF USE</span></strong></p>
				<p style='margin-top:6.0pt;margin-right:0cm;margin-bottom:6.0pt;margin-left:0cm;line-height:17.25pt;font-size:16px;font-family:"Calisto MT","serif";text-align:justify;background:white;'><span style='font-size:15px;font-family:"Calibri","sans-serif";color:#333333;'>Welcome to Astromart.com (the &quot;Site&quot;),&nbsp;</span></p>
				<p style='margin-top:6.0pt;margin-right:0cm;margin-bottom:6.0pt;margin-left:0cm;line-height:17.25pt;font-size:16px;font-family:"Calisto MT","serif";text-align:justify;background:white;'><strong><span style='font-family:"Calibri","sans-serif";color:#333333;'>ACCEPTANCE OF TERMS OF USE</span></strong></p>
				<p style='margin-top:6.0pt;margin-right:0cm;margin-bottom:6.0pt;margin-left:51.0pt;line-height:17.25pt;font-size:16px;font-family:"Calisto MT","serif";text-align:justify;background:white;'><span style='font-size:15px;font-family:"Calibri","sans-serif";color:#333333;'>Please read the following terms and conditions as these terms of use (&quot;Terms&quot;) constitute a legally binding agreement between you and the Company regarding your use of the Site and/or the services provided by the Company, which include but are not limited to aggregation of important news, newsletters, an analysis focusing on IT industry or availability of various types of Content through the Site or any mobile or internet connected device or otherwise (the &ldquo;Services&rdquo;)</span></p>
				<p style='margin-top:6.0pt;margin-right:0cm;margin-bottom:6.0pt;margin-left:51.0pt;line-height:17.25pt;font-size:16px;font-family:"Calisto MT","serif";text-align:justify;background:white;'><span style='font-size:15px;font-family:"Calibri","sans-serif";color:#333333;'>You also represent that you are an individual and not a corporation.</span></p>
				<p style='margin-top:6.0pt;margin-right:0cm;margin-bottom:6.0pt;margin-left:51.0pt;line-height:17.25pt;font-size:16px;font-family:"Calisto MT","serif";text-align:justify;background:white;'><span style='font-size:15px;font-family:"Calibri","sans-serif";color:#333333;'>The Company reserves the right, at its discretion, to change, modify, add, or remove portions of these Terms at any time by posting the amended Terms. Accordingly, please check these Terms periodically for changes. Your continued use of the Site or Services after posting changes constitutes your binding acceptance of such changes. In addition, when using any particular services, you may be subject to any posted guidelines, rules, product requirements or sometimes additional terms applicable to such services. All such guidelines, rules, product requirements or sometimes additional terms are now incorporated by reference into the Terms.</span></p>
				<p style='margin-top:6.0pt;margin-right:0cm;margin-bottom:6.0pt;margin-left:51.0pt;line-height:17.25pt;font-size:16px;font-family:"Calisto MT","serif";text-align:justify;background:white;'><span style='font-size:15px;font-family:"Calibri","sans-serif";color:#333333;'>Further, the Company reserves the right to suspend/cancel, or discontinue any or all channels, products or services at any time without notice, make modifications and alterations in any or all of the Content, products and services contained on the Site without prior notice</span></p>
				<p style='margin-top:6.0pt;margin-right:0cm;margin-bottom:6.0pt;margin-left:51.0pt;line-height:17.25pt;font-size:16px;font-family:"Calisto MT","serif";text-align:justify;background:white;'><span style='font-size:15px;font-family:"Calibri","sans-serif";color:#333333;'>YOUR ACCESS OR USE OF THE SITE OR SERVICE SHALL MEAN YOU READ, UNDERSTAND AND AGREE TO BE BOUND BY THE TERMS.&nbsp;</span></p>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:0cm;line-height:normal;font-size:16px;font-family:"Calisto MT","serif";text-align:justify;background:white;'><strong><span style='font-family:"Calibri","sans-serif";color:maroon;'>1. Description Of Astromart.com:</span></strong></p>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:0cm;line-height:normal;font-size:16px;font-family:"Calisto MT","serif";text-align:justify;background:white;'><span style='font-size:15px;font-family:"Calibri","sans-serif";color:#434343;'>Astromart provides astrological Content, reports, data, telephone, SMS, email and telephonic consultations Content via the World Wide Web, electronic mail, and mobile telephone, telephone, SMS and mobile/ tablet applications. Although portions of the Content may be viewed simply by visiting Astromarts.com (the General Services) to access the personalized astrological zone and/or receive additional Content and services (including telephone-based services) from Astromarts.com (the Personalized Services), you shall need to register as a member of Astromarts.com.</span></p>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:0cm;line-height:normal;font-size:16px;font-family:"Calisto MT","serif";text-align:justify;background:white;'><strong><span style='font-family:"Calibri","sans-serif";color:maroon;'>2. The General Services and the Personalized Services</span></strong></p>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:0cm;line-height:normal;font-size:16px;font-family:"Calisto MT","serif";text-align:justify;background:white;'><span style='font-family:"Calibri","sans-serif";color:#434343;'>Have been referred to collectively as &lsquo;Services&rsquo; in these Terms of Service. When a member avails any of the Personalized Services, the member agrees to:<br>&nbsp;&ndash; Provide the requisite amount of current, relevant, complete, and accurate information about themselves, as and when prompted to do so by Astromarts.com<br>&nbsp;&ndash; Maintain and update this information, as and when required, to keep it current, complete and accurate.<br>&nbsp;&ndash; Please note that all information that We request and You provide on original sign-up, and all updates thereto, are referred to in these Terms of Service as Registration Data.</span></p>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:0cm;line-height:normal;font-size:16px;font-family:"Calisto MT","serif";text-align:justify;background:white;'><span style='font-family:"Calibri","sans-serif";color:#434343;'>&nbsp;</span></p>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:0cm;line-height:normal;font-size:16px;font-family:"Calisto MT","serif";text-align:justify;background:white;'><strong><span style='font-family:"Calibri","sans-serif";color:maroon;'>3. Member Eligibility:</span></strong></p>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:0cm;line-height:normal;font-size:16px;font-family:"Calisto MT","serif";text-align:justify;background:white;'><span style='font-family:"Calibri","sans-serif";color:#434343;'>The Services are available only to individuals who can form legally binding contracts under the applicable law. Without limiting the foregoing, minors are not permitted to use the Services (which means, in most jurisdictions, those under the age of 18).</span></p>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:0cm;line-height:normal;font-size:16px;font-family:"Calisto MT","serif";text-align:justify;background:white;'><strong><span style='font-family:"Calibri","sans-serif";color:maroon;'>4. Member Registration Data:</span></strong></p>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:0cm;line-height:normal;font-size:16px;font-family:"Calisto MT","serif";text-align:justify;background:white;'><span style='font-family:"Calibri","sans-serif";color:#434343;'>Upon registration, including your provision of Registration Data, you will receive a unique Astromarts.com identification (ID) and a password. You shall be entirely responsible for maintaining the confidentiality of your Astromarts.com ID and password. You shall be responsible for all uses of your account, whether or not actually or expressly authorized by you. You may change your password by following the instructions on the website. You agree that your account, ID, and password may not be transferred or sold to another party. You shall also agree to immediately notify Astromarts.com of any unauthorized use of your account or any other breach of security known to you.</span></p>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:0cm;line-height:normal;font-size:16px;font-family:"Calisto MT","serif";text-align:justify;background:white;'><strong><span style='font-family:"Calibri","sans-serif";color:maroon;'>5. Our Access To Your Account:</span></strong></p>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:0cm;line-height:normal;font-size:16px;font-family:"Calisto MT","serif";text-align:justify;background:white;'><span style='font-family:"Calibri","sans-serif";color:#434343;'>In order to ensure that Astromarts.com can provide high-quality services, respond to customer needs, and comply with laws, you shall, with this consent to Astromarts.com employees and agents being able to access your account and records on a case-by-case basis to investigate complaints or other allegations or suspected abuse.</span></p>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:0cm;line-height:normal;font-size:16px;font-family:"Calisto MT","serif";text-align:justify;background:white;'><strong><span style='font-family:"Calibri","sans-serif";color:maroon;'>6. Privacy Policy:</span></strong></p>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:0cm;line-height:normal;font-size:16px;font-family:"Calisto MT","serif";text-align:justify;background:white;'><span style='font-family:"Calibri","sans-serif";color:#434343;'>The privacy of our customers and subsidiaries is very important to us, and thus is our Privacy Policy. This Privacy Policy may be updated occasionally, and the changes shall be incorporated into these Terms of Service for reference. We may amend our Privacy Policy from time to time according to the terms for amending these Terms of Service.</span></p>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:0cm;line-height:normal;font-size:16px;font-family:"Calisto MT","serif";text-align:justify;background:white;'><span style='font-family:"Calibri","sans-serif";color:#434343;'>&nbsp;</span></p>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:0cm;line-height:normal;font-size:16px;font-family:"Calisto MT","serif";text-align:justify;background:white;'><span style='font-size:15px;font-family:"Calibri","sans-serif";color:#333333;'>&nbsp;</span></p>
				<p style='margin-top:6.0pt;margin-right:0cm;margin-bottom:6.0pt;margin-left:14.2pt;line-height:107%;font-size:16px;font-family:"Calisto MT","serif";text-align:justify;'><span style='font-size:13px;line-height:107%;font-family:"Calibri","sans-serif";'>&nbsp;</span></p>
					
			</div>
			<button class="btn btn-primary btn-block btn-lg mt-3" type="button" style="width:auto !important;"><a href="home.php	" style="text-decoration:none;color:white;">Accept & Proceed</a></button>
		</div>
		</div>
     
    </section> 
	
</main>
 <?php include("includes/footer.php");?>
